### PR TITLE
Lab 1

### PR DESCRIPTION
**Pull request by Seven-13**
@Pandadrake

### CODE REVIEW

**Comment by Seven-13** [comment]
@tprewitt425 I'm trying to give you a pull request... not sure it's working!

**Comment by tprewitt425** [comment]
overall looks good. try using the command 'stairs' to connect the lines on the poisson discretely

**Comment by Seven-13** [comment]
(Is this how people reply?) Thanks! I'll try that.

**Comment by Seven-13** [comment]
@Pandadrake see it now?

**Comment by Pandadrake** [comment]
Explanations are clear and the organization and use of function makes it easier to differentiate between the code and text.

**Comment by Seven-13** [comment]
@AlexSchuy pull request for lab 1

**Pull request merged**
